독립 변수 x가 2개 이상인 경우에 대한 학습

# 다중 선형 회귀

In [5]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers

In [6]:
# 중간 고사, 기말 고사, 가산점 점수
X_train = np.array([
    [70,85,11],
    [71,89,18],
    [50,80,20],
    [99,20,10],
    [50,10,10]
]) 
y = np.array([73, 82 ,72, 57, 34]) 

model = Sequential()
model.add(Dense(1, input_dim=3, activation="linear"))

sgd = optimizers.SGD(lr=.0001)
model.compile(optimizer=sgd, loss="mse", metrics=["mse"])
model.fit(X_train, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 153ms/step - loss: 2302.7983 - mse: 2302.7983
Epoch 2/2000
1/1 [==============================] - 0s 6ms/step - loss: 1309.4135 - mse: 1309.4135
Epoch 3/2000


/Users/kim-gwangsu/anaconda3/envs/tf/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)
2023-07-06 19:30:05.688325: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 5ms/step - loss: 754.5235 - mse: 754.5235
Epoch 4/2000
1/1 [==============================] - 0s 6ms/step - loss: 441.2257 - mse: 441.2257
Epoch 5/2000
1/1 [==============================] - 0s 6ms/step - loss: 262.2301 - mse: 262.2301
Epoch 6/2000
1/1 [==============================] - 0s 5ms/step - loss: 158.6554 - mse: 158.6554
Epoch 7/2000
1/1 [==============================] - 0s 7ms/step - loss: 97.9162 - mse: 97.9162
Epoch 8/2000
1/1 [==============================] - 0s 6ms/step - loss: 61.8060 - mse: 61.8060
Epoch 9/2000
1/1 [==============================] - 0s 6ms/step - loss: 40.0424 - mse: 40.0424
Epoch 10/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.7490 - mse: 26.7490
Epoch 11/2000
1/1 [==============================] - 0s 9ms/step - loss: 18.5250 - mse: 18.5250
Epoch 12/2000
1/1 [==============================] - 0s 6ms/step - loss: 13.3755 - mse: 13.3755
Epoch 13/2000
1/1 [==============================] -

In [7]:
model.predict(X_train)

1/1 [==============================] - 0s 39ms/step


2023-07-06 19:30:24.944906: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[72.927864],
       [81.977615],
       [72.09687 ],
       [57.117462],
       [33.80349 ]], dtype=float32)

In [9]:
X_test = np.array([
    [20, 99, 10],
    [40, 50, 20]
])

model.predict(X_test)

1/1 [==============================] - 0s 44ms/step


array([[57.893776],
       [56.0626  ]], dtype=float32)

# 다중 로지스틱 회귀

In [11]:
# 입력값이 2이상이면 1이 출력되게 하기
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [0, 2],
    [1, 1],
    [2, 0]
])
y = np.array([0, 0, 0, 1, 1, 1])

model = Sequential()
model.add(Dense(1, input_dim=2, activation="sigmoid"))
model.compile(optimizer="sgd", loss="binary_crossentropy", metrics=["binary_accuracy"])

model.fit(X, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 381ms/step - loss: 0.7395 - binary_accuracy: 0.6667
Epoch 2/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.7388 - binary_accuracy: 0.6667
Epoch 3/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.7382 - binary_accuracy: 0.6667
Epoch 4/2000
1/1 [==============================] - ETA: 0s - loss: 0.7375 - binary_accuracy: 0.6667

2023-07-06 19:35:07.550954: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 6ms/step - loss: 0.7375 - binary_accuracy: 0.6667
Epoch 5/2000
1/1 [==============================] - 0s 8ms/step - loss: 0.7368 - binary_accuracy: 0.6667
Epoch 6/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.7362 - binary_accuracy: 0.6667
Epoch 7/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.7355 - binary_accuracy: 0.6667
Epoch 8/2000
1/1 [==============================] - 0s 8ms/step - loss: 0.7349 - binary_accuracy: 0.6667
Epoch 9/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.7342 - binary_accuracy: 0.6667
Epoch 10/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.7336 - binary_accuracy: 0.6667
Epoch 11/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.7329 - binary_accuracy: 0.6667
Epoch 12/2000
1/1 [==============================] - 0s 8ms/step - loss: 0.7323 - binary_accuracy: 0.6667
Epoch 13/2000
1/1 [==============================] - 0s 6ms/step 

In [12]:
model.predict(X)

1/1 [==============================] - 0s 30ms/step


2023-07-06 19:36:12.162616: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.17202863],
       [0.45793176],
       [0.44668677],
       [0.7745134 ],
       [0.7664868 ],
       [0.7582638 ]], dtype=float32)